### ISSUE TITLE
Metadata values must be strings. 

### ISSUE THREAD

**Issue by sjrojanooo** [jeppe742/DeltaLakeReader#49]
Prior to commit: 
Traceback (most recent call last):
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/main.py", line 15, in <module>
    main()
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/main.py", line 10, in main
    delta_table = DeltaTable(delta_table_path, file_system=fs)
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/deltalake/deltatable.py", line 45, in __init__
    self._as_newest_version()
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/deltalake/deltatable.py", line 144, in _as_newest_version
    self._apply_from_checkpoint(checkpoint_info["version"])
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/deltalake/deltatable.py", line 87, in _apply_from_checkpoint
    self.schema = schema_from_string(schema_string)
  File "/Users/stevenrojano/Desktop/DeltaLakeReader/deltalake/schema.py", line 17, in schema_from_string
    fields.append(pa.field(name, pa_type, nullable=nullable, metadata=metadata))
  File "pyarrow/types.pxi", line 1759, in pyarrow.lib.field
  File "pyarrow/types.pxi", line 1013, in pyarrow.lib.ensure_metadata
  File "pyarrow/types.pxi", line 915, in pyarrow.lib.KeyValueMetadata.__init__
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, int found

 https://github.com/jeppe742/DeltaLakeReader/pull/48

**Comment by jeppe742** [comment]
Hey @sjrojanooo Thanks for the issue, and PR. Will have a look later today 😃

**Comment by sjrojanooo** [comment]
@jeppe742 you're welcome! Happy to help.

**Comment by jeppe742** [comment]
Hey @sjrojanooo 
Sorry about the wait, had some issues getting the tests to run.
Have published your suggested change in version 0.2.14
